"""
Django settings for SupplyAPI project.
Generated by 'django-admin startproject' using Django 5.0.6.
"""

import os
import socket
from datetime import timedelta
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Security
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'False').lower() in ['true', '1', 't']
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost').split(',')

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.auth.CookieJWTAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_COOKIE': 'access_token',
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_SECURE': os.getenv('AUTH_COOKIE_SECURE', 'False').lower() in ['true', '1', 't'],
    'AUTH_COOKIE_SAMESITE': 'Strict',
    'CSRF_COOKIE_SECURE': os.getenv('CSRF_COOKIE_SECURE', 'False').lower() in ['true', '1', 't'],
    'SESSION_COOKIE_SECURE': os.getenv('SESSION_COOKIE_SECURE', 'False').lower() in ['true', '1', 't'],
}

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://supply-management-system.netlify.app",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "https://supply-management-system.netlify.app",
]

AUTH_USER_MODEL = 'api.CustomUser'

# Email
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Applications
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'rest_framework_simplejwt.token_blacklist',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'rest_framework',
    'corsheaders',
    'django_filters',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SupplyAPI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SupplyAPI.wsgi.application'

# Environment & DB setup
IS_LOCALHOST = socket.gethostname() in ['localhost', '127.0.0.1', '::1']
ENVIRONMENT = os.getenv('DJANGO_ENV', 'development')
IS_USER_ACTIVATION_ENABLED = os.getenv('IS_USER_ACTIVATION_ENABLED', 'True').lower()

print(f'\nRunning in {ENVIRONMENT} Mode.\n')

# Database Configuration
DATABASES = {'default': {}}

# Local PostgreSQL (development)
if IS_LOCALHOST or ENVIRONMENT == 'development':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('HOST'),
            'PORT': os.getenv('PORT'),
        }
    }
    print(f"✅ Using LOCAL PostgreSQL database: {os.getenv('DB_NAME')}")

# Test environment
elif ENVIRONMENT == 'test':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_TEST_NAME'),
            'USER': os.getenv('DB_TEST_USER'),
            'PASSWORD': os.getenv('DB_TEST_PASSWORD'),
            'HOST': os.getenv('TEST_HOST'),
            'PORT': os.getenv('TEST_PORT'),
        }
    }
    print(f" Using TEST database: {os.getenv('DB_TEST_NAME')}")

# Production (Render/Supabase - PostgreSQL)
else:
    # Try to use DATABASE_URL first (for Render/Supabase)
    database_url = os.getenv('DATABASE_URL')
    if database_url:
        DATABASES['default'] = dj_database_url.config(
            default=database_url,
            conn_max_age=600,
            ssl_require=True
        )
        print(" Using PostgreSQL via DATABASE_URL (Production)")
    else:
        # Fallback to individual PostgreSQL settings
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': os.getenv('TIDB_DB_NAME'),  
                'USER': os.getenv('TIDB_USER'),
                'PASSWORD': os.getenv('TIDB_PASSWORD'),
                'HOST': os.getenv('TIDB_HOST'),
                'PORT': int(os.getenv('TIDB_PORT', 5432)),
                'OPTIONS': {
                    'sslmode': 'require',
                },
            }
        }
        print("✅ Using PostgreSQL with individual settings (Production)")

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Localization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}', 'style': '{'},
        'simple': {'format': '{levelname} {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'verbose'},
        'file': {'class': 'logging.FileHandler', 'filename': 'debug.log', 'formatter': 'verbose'},
    },
    'loggers': {
        'django': {'handlers': ['console', 'file'], 'level': 'INFO'},
        'api': {'handlers': ['console', 'file'], 'level': 'DEBUG', 'propagate': True},
    },
    'root': {'handlers': ['console', 'file'], 'level': 'INFO'},
}